 /******************************************************************************
 * ultrasonic.c
 *
 *  Created on: Oct 13, 2024
 *      Author: Malak
 *******************************************************************************/

#include<util/delay.h>
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include "common_macros.h"
#include <math.h>

uint8 edgeCount = 0;
ICU_ConfigType ICU_Configuration ={F_CPU_8, RAISING};
uint16 g_period = 0;
uint16 distance = 0;

/*
 * Description:
 * Initialize the ICU driver as required.
 * Set up the ICU callback function.
 * Set the direction for the trigger pin as output through the GPIO driver
 */
 void Ultrasonic_init(void)
 {
	 ICU_init(&ICU_Configuration);
	 ICU_setCallBack(Ultrasonic_edgeProcessing);
	 GPIO_setupPinDirection(Ultrasonic_PORT_ID, Ultrasonic_TRIGGER_PIN_ID, PIN_OUTPUT);
 }

 /*
  * Description:
  * Send the trigger pulse to the ultrasonic sensor
  */
 void Ultrasonic_Trigger(void)
 {
	 GPIO_writePin(Ultrasonic_PORT_ID, Ultrasonic_TRIGGER_PIN_ID, LOGIC_HIGH);
	 _delay_ms(0.1);
	 GPIO_writePin(Ultrasonic_PORT_ID, Ultrasonic_TRIGGER_PIN_ID, LOGIC_LOW);
 }

 /*
  *  Description:
  *  Send the trigger pulse by using the Ultrasonic_Trigger function.
  *  Start the measurement process via the ICU driver
  */
 uint16 Ultrasonic_readDistance(void)
 {
	 Ultrasonic_Trigger();
	 distance =ceil((g_period) * (float)(1/ 117.6));
	 g_period = 0;
	 edgeCount = 0;
	 return distance;
 }

 /*
  *  Description:
  *	 This is the callback function called by the ICU driver.
  *	 It calculates the high time (pulse time) generated by the ultrasonic sensor
  */
 void Ultrasonic_edgeProcessing(void)
 {
	 edgeCount++;
	 if(edgeCount == 1)
	 {
		 ICU_clearTimerValue();
		 ICU_setEdgeDetectionType(FALLING);
	 }
	 else if(edgeCount == 2)
	 {
		 g_period = ICU_getInputCaptureValue();
		 ICU_clearTimerValue();
		 ICU_setEdgeDetectionType(RAISING);
	 }
 }


